// keeping the app static :) 
const foodPrompts = [
  "croissant",
  "cupcake",
  "pizza",
  "fried chicken",
  "sushi",
  "waffles",
  "doughnuts",
  "ice cream",
  "olives",
  "cocktail",
  "biscuits",
  "hamburger",
  "cheese",
  "chocolate",
  "coffee",
  "jam",
  "pancakes",
  "sourdough",
  "toast",
  "peanut butter",
  "bubble tea",
  "siracha",
  "strawberry shortcake",
  "hotdog",
  "burrito",
  "banana split",
  "dimsum",
  "bagel",
  "carpaccio",
  "pretzel"
];

const fruitPrompts = [
  "dragonfruit",
  "fig",
  "lemon",
  "papaya",
  "avocado",
  "clementines",
  "bananas",
  "strawberries",
  "apples",
  "grapes",
  "pineapple",
  "cherries",
  "kiwi",
  "pears",
  "coconuts",
];

const animalPrompts = [
  "turtle",
  "penguin",
  "monkey",
  "fox",
  "cuttlefish",
  "whale",
  "rat",
  "parrot",
  "koala",
  "cow",
  "chicken",
  "pig",
  "frog",
  "walrus",
  "zebra",
  "iguana",
  "elephant",
  "alpaca",
  "owl",
  "cat",
  "bear",
  "anteater",
  "eagle",
  "kangaroo"
];

const flowerPrompts = [
  "sunflower",
  "cherry blossoms",
  "tulips",
  "gerbera daisy",
  "carnation",
  "waterlily",
  "iris",
  "rose",
  "lavender",
  "magnolias",
  "pansy",
  "daffodil",
  "poppy",
  "marigold",
  "king protea",
  "calla lily",
  "anthurium",
  "amaryllis",
  "lily of the valley",
  "bluebells",
  "orchids",
  "dahlia",
  "hydrangea",
  "clematis",
  "hibiscus"
];

const insectPrompts = [
  "butterfly",
  "moth",
  "beetle",
  "ladybug",
  "caterpillar",
  "bee",
  "dragonfly",
  "praying mantis",
  "grasshopper",
  "tarantula",
  "wasp",
  "centipede",
  "ant",
  "iris weevil",
  "waterbug",
  "stink bug",
  "fruit fly",
  "mosquito",
  "cockroach"
];

const plantPrompts = [
  "cactus",
  "monstera",
  "rosemary",
  "yucca",
  "zebra plant",
  "string of pearls",
  "snake plant",
  "basil",
  "Fiddle leaf fig",
  "spider plant",
  "aloe vera",
  "parlor palm",
  "pilea peperomioides",
  "bamboo",
  "parsley",
  "rubber plant",
  "english ivy",
  "boston fern",
  "banana plant",
  "purple smoke bush",
  "philohendron",
  "calathea orbifolia",
  "ruffled fan palm",
  "money tree plant",
  "birds of paradise"
];

const baseTopics = {
  "food": foodPrompts,
  "animal": animalPrompts,
  "flower": flowerPrompts,
  "fruit": fruitPrompts,
  "insect": insectPrompts,
  "plant": plantPrompts
};

var basicTopicsList =  [];